services:
  gigmaster:
    build: .
    container_name: gigmaster
    ports:
      - "8080:80"
    volumes:
      # local lyrics folder
      - ./app:/app
    restart: unless-stopped
    user: ${CURRENT_UID}
